[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.128.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.128.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.128.0"
